// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"goods/rpc/goods"
	"goods/rpc/internal/logic"
	"goods/rpc/internal/svc"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServer) GetGoodsByIds(ctx context.Context, in *goods.GetGoodsByIdsRequest) (*goods.GetGoodsByIdsResponse, error) {
	l := logic.NewGetGoodsByIdsLogic(ctx, s.svcCtx)
	return l.GetGoodsByIds(in)
}

func (s *GoodsServer) UpdateStock(ctx context.Context, in *goods.UpdateStockRequest) (*goods.UpdateStockResponse, error) {
	l := logic.NewUpdateStockLogic(ctx, s.svcCtx)
	return l.UpdateStock(in)
}
